batch_size: 6

max_shown_songs: 25 # The maximum number of songs to show when displaying the song queue
spotify_song_limit: 150 # The maximum number of songs to add from a spotify playlist
inactivity_timeout: 600 # After this amount of time (in seconds), the bot will disconnect

record_stats: false # Record stats in a database. If false, will eliminate all read/write operations to/from database
reset_database: true # Drop all usage data
get_usage_graph_with_stats: false # Feature flag to get a graph of bot usage for the stats command

enable_multiprocessing: true