reset_database: false # Drop all usage data
max_shown_songs: 20 # The maximum number of songs to show when displaying the song queue
spotify_song_limit: 100 # The maximum number of songs to add from a spotify playlist
inactivity_timeout: 600 # After this amount of time (in seconds), the bot will disconnect

get_usage_graph_with_stats: false # Feature flag to get a graph of bot usage for the stats command